[webservers]
35.154.113.204

[webservers:vars]
ansible_user                 = ubuntu
ansible_ssh_private_key_file = ~/.ssh/iac-demo-key-v3.pem
ansible_ssh_common_args      = '-o StrictHostKeyChecking=no'
ansible_python_interpreter   = /usr/bin/python3
